### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by cpanato** [google/pullsheet#9]
Add CI jobs to validate and test, can be github actions

if that sounds good I can help to setup that

**Comment by tstromberg** [comment]
Sounds great! I would definitely would like to see this happen, as it makes code reviews substantially easier.

**Comment by cpanato** [comment]
and github actions is something you want? or another like circleci?

**Comment by tstromberg** [comment]
In my experience, GitHub actions provides a better experience for projects of this size.

**Comment by cpanato** [comment]
ok, i will work over the weekend and add some makeFile and golangci-lint rules as well
